In [4]:
import numpy as np 
import pandas as pd 
from datetime import datetime
import datetime as dt

In [2]:
data = pd.read_csv('merged_ecommerce.csv')
data.head()

/var/folders/s5/1203q68j6lqgl604z3g6p36w0000gn/T/ipykernel_74348/2867737603.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('merged_ecommerce.csv')

,Unnamed: 0,InvoiceNo,ASIN,Quantity,price,total_sale,invoice_date,invoice_time,CustomerID,ASIN.1,title,product_type,CustomerID.1,Country,rating,review_count,ASIN.2,StockCode,ASIN.3
0,0,78536597,B07GWKDLGT,4,496.95,1987.80,2018-12-01,17,18011,B07GWKDLGT,Nikon D3500 W/ AF-P DX NIKKOR 18-55mm f/3.5-5....,dslr camera,18011,Germany,4.6,1399,B07GWKDLGT,21703,B07GWKDLGT
1,1,78536597,B01MTLH408,4,39.99,159.96,2018-12-01,17,18011,B01MTLH408,"Manfrotto Element Aluminum 5-Section Monopod, ...",dslr camera,18011,Germany,4.6,289,B01MTLH408,40001,B01MTLH408
2,2,78536597,B0064FS7HI,1,12.99,12.99,2018-12-01,17,18011,B0064FS7HI,"STK LP-E8 Battery for Canon Rebel T5i, T3i, T2...",dslr camera,18011,Germany,4.4,333,B0064FS7HI,85034A,B0064FS7HI
3,3,78536597,B013JHU5YG,1,199.99,199.99,2018-12-01,17,18011,B013JHU5YG,Lowepro Whistler BP 350 AW (Grey) . Profession...,dslr camera,18011,Germany,4.3,86,B013JHU5YG,72798C,B013JHU5YG
4,4,78536597,B06XWN9Q99,1,7.49,7.49,2018-12-01,17,18011,B06XWN9Q99,Samsung (MB-ME32GA/AM) 32GB 95MB/s (U1) microS...,dslr camera,18011,Germany,4.7,15717,B06XWN9Q99,20726,B06XWN9Q99

In [3]:
data_clean = data.drop(columns= ["Unnamed: 0", "ASIN.1", "ASIN.2", "ASIN.3", "CustomerID.1"])
data_clean.head()

,InvoiceNo,ASIN,Quantity,price,total_sale,invoice_date,invoice_time,CustomerID,title,product_type,Country,rating,review_count,StockCode
0,78536597,B07GWKDLGT,4,496.95,1987.80,2018-12-01,17,18011,Nikon D3500 W/ AF-P DX NIKKOR 18-55mm f/3.5-5....,dslr camera,Germany,4.6,1399,21703
1,78536597,B01MTLH408,4,39.99,159.96,2018-12-01,17,18011,"Manfrotto Element Aluminum 5-Section Monopod, ...",dslr camera,Germany,4.6,289,40001
2,78536597,B0064FS7HI,1,12.99,12.99,2018-12-01,17,18011,"STK LP-E8 Battery for Canon Rebel T5i, T3i, T2...",dslr camera,Germany,4.4,333,85034A
3,78536597,B013JHU5YG,1,199.99,199.99,2018-12-01,17,18011,Lowepro Whistler BP 350 AW (Grey) . Profession...,dslr camera,Germany,4.3,86,72798C
4,78536597,B06XWN9Q99,1,7.49,7.49,2018-12-01,17,18011,Samsung (MB-ME32GA/AM) 32GB 95MB/s (U1) microS...,dslr camera,Germany,4.7,15717,20726

In [11]:
data_clean["invoice_date"] = pd.to_datetime(data_clean["invoice_date"])

display(data_clean.info(),data_clean.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 554417 entries, 0 to 554416
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   InvoiceNo     554417 non-null  object
 1   ASIN          554417 non-null  object
 2   Quantity      554417 non-null  int64
 3   price         554417 non-null  float64
 4   total_sale    554417 non-null  float64
 5   invoice_date  554417 non-null  datetime64[ns]
 6   invoice_time  554417 non-null  int64
 7   CustomerID    554417 non-null  object
 8   title         554417 non-null  object
 9   product_type  554417 non-null  object
 10  Country       554417 non-null  object
 11  rating        554417 non-null  float64
 12  review_count  554417 non-null  int64
 13  StockCode     554417 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(7)
memory usage: 59.2+ MB

None

InvoiceNo       0
ASIN            0
Quantity        0
price           0
total_sale      0
invoice_date    0
invoice_time    0
CustomerID      0
title           0
product_type    0
Country         0
rating          0
review_count    0
StockCode       0
dtype: int64

In [12]:
(data['CustomerID']=='Null').value_counts()

False    415102
True     139315
Name: CustomerID, dtype: int64

In [14]:
# Replace string 'Null' with null value
data_clean =data_clean.replace({'Null': None})
data_clean.head()

,InvoiceNo,ASIN,Quantity,price,total_sale,invoice_date,invoice_time,CustomerID,title,product_type,Country,rating,review_count,StockCode
0,78536597,B07GWKDLGT,4,496.95,1987.80,2018-12-01,17,18011,Nikon D3500 W/ AF-P DX NIKKOR 18-55mm f/3.5-5....,dslr camera,Germany,4.6,1399,21703
1,78536597,B01MTLH408,4,39.99,159.96,2018-12-01,17,18011,"Manfrotto Element Aluminum 5-Section Monopod, ...",dslr camera,Germany,4.6,289,40001
2,78536597,B0064FS7HI,1,12.99,12.99,2018-12-01,17,18011,"STK LP-E8 Battery for Canon Rebel T5i, T3i, T2...",dslr camera,Germany,4.4,333,85034A
3,78536597,B013JHU5YG,1,199.99,199.99,2018-12-01,17,18011,Lowepro Whistler BP 350 AW (Grey) . Profession...,dslr camera,Germany,4.3,86,72798C
4,78536597,B06XWN9Q99,1,7.49,7.49,2018-12-01,17,18011,Samsung (MB-ME32GA/AM) 32GB 95MB/s (U1) microS...,dslr camera,Germany,4.7,15717,20726

In [16]:
data_clean.isnull().sum()

InvoiceNo            0
ASIN              8398
Quantity             0
price                0
total_sale           0
invoice_date         0
invoice_time         0
CustomerID      139315
title                0
product_type         0
Country              0
rating               0
review_count         0
StockCode            0
dtype: int64

In [17]:
data_clean.shape

(554417, 14)

In [19]:
# Dropping rows having missing values
data_clean = data_clean.dropna()
data_clean.shape

(409035, 14)

In [20]:
data_clean.head()

,InvoiceNo,ASIN,Quantity,price,total_sale,invoice_date,invoice_time,CustomerID,title,product_type,Country,rating,review_count,StockCode
0,78536597,B07GWKDLGT,4,496.95,1987.80,2018-12-01,17,18011,Nikon D3500 W/ AF-P DX NIKKOR 18-55mm f/3.5-5....,dslr camera,Germany,4.6,1399,21703
1,78536597,B01MTLH408,4,39.99,159.96,2018-12-01,17,18011,"Manfrotto Element Aluminum 5-Section Monopod, ...",dslr camera,Germany,4.6,289,40001
2,78536597,B0064FS7HI,1,12.99,12.99,2018-12-01,17,18011,"STK LP-E8 Battery for Canon Rebel T5i, T3i, T2...",dslr camera,Germany,4.4,333,85034A
3,78536597,B013JHU5YG,1,199.99,199.99,2018-12-01,17,18011,Lowepro Whistler BP 350 AW (Grey) . Profession...,dslr camera,Germany,4.3,86,72798C
4,78536597,B06XWN9Q99,1,7.49,7.49,2018-12-01,17,18011,Samsung (MB-ME32GA/AM) 32GB 95MB/s (U1) microS...,dslr camera,Germany,4.7,15717,20726

In [ ]:
a =